[package]
name = "wasmi-test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.94"
wasmtime = "27.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
regex = "1.10"
clap = { version = "4.0", features = ["derive"] }
sha2 = "0.10.8"
hex = "0.4.3"