[package]
name = "dynamic_struct"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
serde_json.workspace = true
serde.workspace = true

[build-dependencies]
serde.workspace = true
serde_json.workspace = true